cantabular/pdf2msgpack

- Dockerfile
- wscript
Somehow this was missed before. The effect is for poppler to warn during
configuring that this library is missing and that bad things might happen.
> Add turbojpeg dependency

- src/main.cpp
Previously it was uninitialized. Now I give it a default constructor and do it explicitly.
We didn't spot this before because the compilation environment happened to have it zero initialized, but not the environment in which we make our production executables...
> Zero initialize Options

- src/DumpPathsAsMsgPackDev.h
- src/main.cpp
It doesn't make sense to interpret the coordinates without
applying the transformation matrix state to them.
This PR introduces a minimal Mat2x3 implementation which just
implements `mul()` and returns a point.
Also, now the path coordinates use the same coordinate system as the text.
> Apply transformation matrix to path coordinates

- src/main.cpp
Requires an update to our reader.
> Write pages directly to output instead of as an array

- src/main.cpp
- wscript
Automatically delete things when they go out of scope using `unique_ptr`
rather than explicitly deleting.
> Use C++11 memory management

- .dockerignore
- src/main.cpp
**BUMPS OUTPUT VERSION**.
Now Pages are represented with a map with the following keys:
`{"Size": (w, h), "Glyphs": [], "Paths": []}` and optionally
`{"Bitmap": bytes}`.
The bitmap is only rendered if `--bitmap` is supplied.
> Add --bitmap, make page into a map rather than array

- src/main.cpp
- wscript
I had mistyped the syscall-reporter.cpp filename and it was being
silently not included.
Also, we had a dependency on a header which was absent.
Closes #21.
> Fix conditional syscall-reporter

- src/main.cpp
It turns out font-info can be very slow since it inspects the objects of
every page. This can delay time-to-first-byte quite a bit (many seconds).
Therefore, this PR makes it optional and default to off.
> Add --font-info (default off)

- src/DumpAsTextDev.h
- src/DumpPathsAsMsgPackDev.h
- src/main.cpp
- wscript
Previously we included `poppler/` erroneously.
> Fix poppler include paths

- pdf2msgpack.rb
This should cover all build and runtime dependencies.
To install, run: `brew install https://raw.github.com/scraperwiki/pdf2msgpack/master/pdf2msgpack.rb`.
Some notes:
- Since all formula require to run a test, it would be good if we could have access to a fake mini-pdf to convert or at least a `--version` option to we know it runs.
- We should make a new version (e.g. 0.3) with the latest changes to allow pushing this to the main repo ("tap": _homebrew-core_) so users can just `brew install pdf2msgpack`.
> Add Homebrew formula for easy install on macOS

- src/main.cpp
It is needed even if syscall-reporter is disabled, but not if the filter
is disabled.
> Fix logic for including seccomp-bpf.h

- src/DumpPathsAsMsgPackDev.h
* Stroke (color, width)
* Fill (stroke, fill color)
Information is encoded onto the stream by writing elements into the path
list with SET_FILL_COLOR, SET_STROKE_COLOR and SET_STROKE_WIDTH.
* Style information is only written when it changes, rather than for every object.
* Colour starts off black.
* Line width is always given in the stream when we first encounter a line.
* Should be backwards compatible, because readers will just drop elements they don't understand.
Remember: 
```c
const int EO_FILL = 10;
const int STROKE = 11;
const int FILL = 12;
const int SET_STROKE_COLOR = 13;
const int SET_STROKE_WIDTH = 14;
const int SET_FILL_COLOR = 15;
```
```
[1,
{b'Creator': b'cairo 1.13.1 (http://cairographics.org)',
b'FileName': b'test_paths.pdf',
b'FontInfo': None,
b'Pages': 1,
b'Producer': …
```
> Add line style information

- src/main.cpp
These are all the significnat cases I could find where we write ints to the wire.
Fixes #26.
> Use fixed-size ints in msgpack

- go/README.md
- go/p2m-reader/main.go
- go/p2m/decode.go
- go/p2m/msgp.go
- go/p2m/msgp_gen.go
- go/p2m/msgp_gen_test.go
First attempt at a go decoder.
I sort of wish I had done this before, since it highlights various ways that
the format is not ideal.
It makes heavy use of the `msgp` code which can be `go generate`'d, except
for Meta.FontInfos, which is mishandled and had to be manually fixed. I'll
file a bug upstream for that.
TODO:
- Also some code which invokes pdf2msgpack and parses that output.
> Add go decoder

- Dockerfile
- Makefile
- src/DumpAsTextDev.h
- src/DumpPathsAsMsgPackDev.h
- src/main.cpp
- wscript
This PR updates to poppler-0.73.0. We do it via 0.70.1 since .71 was invasive.
This could do with a bit of additional testing.
> Update to poppler-0.73.0 and use docker buildkit caching

- .gitmodules
Assume these redirect anyway, but no harm in stating https.
> Use https submodule URLs

- Dockerfile
- wscript
This is to make it easier to incrementally test and release versions of pdf2msgpack with each individual dependency change applied.
> Revert dependency updates since 0.7.0

- .gitmodules
- Dockerfile
The resource moved, so we should update to the canonical URL.
The existing URL does apparently still work, but may also be causing problems for Dependabot, so let's try updating it.
> Update Freetype Git URL

- src/DumpPathsAsMsgPackDev.h
Fixes #154.
With this fix, the outputs are deterministic. Without it, in some cases, the outputs are not; for example, they can be very, very small, random floating point values.
In brief, this is because when handling curve subpaths, the code accesses values from subsequent positions in arrays. Poppler represents curves as three successive values; the first two have `curve=true` and the third one `curve=false`.
The code here is similar to that Poppler uses it for iterating through these values in its own `doPath` code. However,  when working with curve values, Poppler's own code then works with a loop increment of `+= 3`. This ensures that only the first point of the curve is handled.
The fundamental problem is that the code accesses the second subsequent array value after `curve=true` …
> Fix output non-determinism

- .gitmodules
- wscript
This has been previously upgraded to, then reverted. This PR undoes the relevant reverts to apply these commits again.
> Restore msgpack v4.1.1

- .gitmodules
- wscript
This PR restores the msgpack v6.1.0 fork with the v4.1.1 float behaviour.
See #147 — in future, we should consider removing this consistency workaround to avoid the need for a fork.
> Restore sensiblecodeio msgpack fork

- Dockerfile
- src/main.cpp
This finally gets us to the current version of Poppler; albeit with the need for two reverted commits.
> Update to Poppler 24.01.0

- go/README.md
- go/cmd/p2m-reader/main.go
- go/go.mod
- go/go.sum
It wasn't adding much to the formatting here, so let's remove it.
We do lose the commas between struct fields, but that's fine.
> Remove use of `pretty` dependency
